dist: xenial
language: python
python:
    - 3.6

cache:
    directories:
        - $HOME/.blender-cache

before_install:
    - sudo apt-get update
    - sudo apt-get install --no-install-recommends -y libsdl1.2debian libglu1 python3-pip
    - sudo pip3 install --upgrade pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install -r requirements.txt

install:
    - bash tests/install_blender.sh
    - source .envs

script:
    - make all BLENDER=$BLENDER_BIN PYLINT=pylint PEP8=pycodestyle
