dist: xenial
language: python
python:
    - 3.7

cache:
    directories:
        - $HOME/.blender-cache

before_install:
    - sudo apt-get update
    - pip install --upgrade pip
    - pip install --upgrade setuptools

install:
    - sudo apt-get install --no-install-recommends -y libsdl1.2debian libglu1 python3-pip
    - pip install -r requirements.txt
    - bash tests/install_blender.sh
    - source .envs

script:
    - make all BLENDER=$BLENDER_BIN PYLINT='python3 -m pylint'
